Controllers/ToyStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToyStore.Models;
using ToyStore.ViewModels;

using PagedList;
using PagedList.Mvc;

namespace ToyStore.Controllers
{
    public class ToyStoreController : Controller
    {
        ToyStoreDataContext data = new ToyStoreDataContext();
        // GET: ToyStore

        private List<HinhAnh_SP> listImg(int product_id)
        {
            return data.HinhAnh_SPs.OrderBy(a => a.id).Where(n => n.product_id == product_id).ToList();
        }
        private List<SanPham> SanPhamMoi (int count)
        {
            return data.SanPhams.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var spmoi = SanPhamMoi(4);
            return View(spmoi);
        }
        public ActionResult DongSP()
        {
            var dongsp = from dong in data.DongSPs select dong;
            return PartialView(dongsp);
        }
        public ActionResult DongSanPham (int id, int ? page)
        {
            int pageSize = 12;
            int pageNum = (page ?? 1);

            var toy = from t in data.SanPhams where t.MaD == id select t;
            ViewBag.Page = pageNum;
            return View(toy.ToPagedList(pageNum, pageSize));
        }

        public ActionResult PhanLoai()
        {
            var phanloai = from pl in data.DongPLs select pl;
            return PartialView(phanloai);
        }
        public ActionResult SPtheoLoai (int id, int ? page)
        {
            int pageSize = 12;
            int pageNum = (page ?? 1);

            var toy = from sp in data.SanPhams
                      join d in data.DongSPs
                      on sp.MaD equals d.MaD
                      where sp.MaPL == id
                      select sp;
            ViewBag.Page = pageNum;
            return View(toy.ToPagedList(pageNum, pageSize));
        }
        public ActionResult BannerAd()
        {
            return PartialView();
        }
        public ActionResult TitlePage()
        {
            return PartialView();
        }
        public ActionResult ImagePro(int id)
        {
            var imgpro = from img in data.HinhAnh_SPs where img.product_id == id select img;
            return PartialView(imgpro);
        }
        public ActionResult Details (int id)
        {
            var model = new DetailProViewModel()
            {
                Detail = data.SanPhams.Where(x => x.MaSP == id).ToList(),
                listImg = data.HinhAnh_SPs.Where(y => y.product_id == id).ToList(),
            };

            return View(model);
        }
        public ActionResult Products (int ? page)
        {
            int pageSize = 12;
            int pageNum = (page ?? 1);
                        
            var sanpham = from sp in data.SanPhams select sp;
            ViewBag.Page = pageNum;
            return View(sanpham.ToPagedList(pageNum, pageSize));
        }

        public ActionResult CollectionPro(int id)
        {
            var collection = (from t in data.SanPhams where t.MaD == id select t).Take(4).ToList();
            return PartialView(collection);
        }

        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult SizeChart()
        {
            return View();
        }
        public ActionResult News()
        {
            return View();
        }
        public ActionResult Error()
        {
            return View();
        }
        public ActionResult Search (string searchString, int ? page)
        {
            int pageSize = 12;
            int pageNum = (page ?? 1);
            var toy = from t in data.SanPhams
                      select t;
            if (!String.IsNullOrEmpty(searchString))
            {
                toy = toy.Where(s => s.TenSP.Contains(searchString));                
            }
            ViewBag.Search = searchString;
            ViewBag.Page = pageNum;
            return View(toy.ToPagedList(pageNum, pageSize));
        }
        public IEnumerable<SanPham> SanPhamDeXuat ()
        {
            Random rand = new Random();
            int ranNum = rand.Next(1, 229);
            return data.SanPhams.ToList().Skip(ranNum).Take(6);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToyStore.Models;
using System.Web.Security;
using ToyStore.common;

namespace ToyStore.Controllers
{
    public class UserController : Controller
    {
        PhoneStoreDataContext data = new PhoneStoreDataContext();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var tendn = collection["TenDN"];
            var hoten = collection["HoTenKH"];
            var ngaysinh = String.Format("{0:dd/MM/yyyy}", collection["NgaySinh"]);
            var sdt = collection["SDT"];
            var diachi = collection["DiaChi"];
            var email = collection["Email"];
            var matkhau = collection["MatKhau"];
            var matkhaunhaplai = collection["MatKhauNhapLai"];
            password EncryptedData = new password();
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Tên đăng nhập không được để trống";
            }
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi2"] = "Tên không được để trống";
            }
            if (String.IsNullOrEmpty(ngaysinh))
            {
                ngaysinh = "01/01/2000";
            }
            if (String.IsNullOrEmpty(sdt))
            {
                ViewData["Loi4"] = "Số điện thoại không được để trống";
            }
            if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi5"] = "Địa chỉ không được để trống";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi6"] = "Email không được để trống";
            }
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi7"] = "Mật khẩu không được để trống";
            }
            if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi8"] = "Mật khẩu không được để trống";
            }
            else if (matkhaunhaplai != matkhau)
            {
                ViewData["Loi9"] = "Mật khẩu không khớp";
            }             
            else
            {
                kh.TaiKhoan = tendn;
                kh.HoTen = hoten;
                kh.NgaySinh = DateTime.Parse(ngaysinh);
                kh.DienThoaiKH = sdt;
                kh.DiachiKH = diachi;
                kh.Email = email;
                kh.MatKhau = EncryptedData.Encode(matkhau);
                if (data.KhachHangs.Any(x => x.TaiKhoan == kh.TaiKhoan))
                {
                    ViewBag.LoiTK = "Tài khoản đã tồn tại";
                }
                else if (data.KhachHangs.Any(x => x.Email == kh.Email))
                {
                    ViewBag.LoiEmail = "Email đã được đăng ký";
                }
                else
                {
                    data.KhachHangs.InsertOnSubmit(kh);
                    data.SubmitChanges();
                    return RedirectToAction("DangNhap");
                }                
            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            if (Session["Taikhoan"] != null)
            {
                return RedirectToAction("Index", "PhoneStore");                
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection, string returnUrl)
        {
            password EncryptedData = new password();
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];

            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Tên đăng nhập không được bỏ trống";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Mật khẩu không được bỏ trống";
            }

            else
            {
                // Biến kiểm tra tendn và matkhau có khớp với db k, nếu ko khớp thì null
                KhachHang kh = data.KhachHangs.SingleOrDefault(model => model.TaiKhoan == tendn && model.MatKhau == EncryptedData.Encode(matkhau));
                if (kh != null)
                {
                    FormsAuthentication.SetAuthCookie(kh.HoTen, false);
                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        //ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                        Session["Taikhoan"] = kh;
                        return RedirectToAction("Index", "PhoneStore");
                    }
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
        public ActionResult DonDatHang(string username)
        {
            KhachHang kh = (KhachHang)Session["Taikhoan"];
            if (Session["Taikhoan"] == null || Session["Taikhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "User");
            }
            else
            {
                return View(data.DonDatHangs.Where(i => i.KhachHang.TaiKhoan == kh.TaiKhoan).ToList().OrderByDescending(n => n.NgayDH));
            }
        }
        public ActionResult Chitietdonhang(string username, int id)
        {
            KhachHang kh = (KhachHang)Session["Taikhoan"];
            if (Session["Taikhoan"] == null || Session["Taikhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "User");
            }
            else
            {
                return View(data.ChiTietDatHangs.ToList().Where(n => n.SoDH == id && n.DonDatHang.KhachHang.TaiKhoan == kh.TaiKhoan).OrderBy(n => n.MaCT));
            }
        }        
        [HttpGet]
        public ActionResult Information()
        {
            KhachHang kh = (KhachHang)Session["Taikhoan"];
            if (Session["Taikhoan"] == null || Session["Taikhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "User");
            }
            else
            {
                return View(data.KhachHangs.Single(n => n.TaiKhoan == kh.TaiKhoan));
            }
        }
        [HttpPost]
        public ActionResult Information(FormCollection collection)
        {
            KhachHang sskh = (KhachHang)Session["Taikhoan"];
            KhachHang kh = data.KhachHangs.Single(n => n.TaiKhoan == sskh.TaiKhoan);
            var hoten = collection["HoTen"];
            var diachi = collection["DiachiKH"];
            var sdt = collection["DienThoaiKH"];
            var ngaysinh = collection["NgaySinh"];

            if (ModelState.IsValid)
            {
                kh.HoTen = hoten;
                kh.DiachiKH = diachi;
                kh.DienThoaiKH = sdt;
                kh.NgaySinh = Convert.ToDateTime(ngaysinh);

                data.SubmitChanges();
            }
            return RedirectToAction("Information");
        }
        [HttpGet]
        public ActionResult ChangePassword()
        {
            KhachHang kh = (KhachHang)Session["Taikhoan"];
            if (kh == null || kh.ToString() == "")
            {
                return RedirectToAction("DangNhap", "User");
            }

            return View(data.KhachHangs.Single(tk => tk.TaiKhoan == kh.TaiKhoan));
        }
        [HttpPost]
        public ActionResult ChangePassword(FormCollection collection)
        {
            KhachHang sskh = (KhachHang)Session["Taikhoan"];
            KhachHang kh = data.KhachHangs.Single(n => n.TaiKhoan == sskh.TaiKhoan);

            var oldpassword = collection["oldpassword"];
            var newpassword = collection["newpassword"];
            var retypepass = collection["retypepass"];
            password EncryptedData = new password();
            if (String.IsNullOrEmpty(oldpassword) || String.IsNullOrEmpty(newpassword) || String.IsNullOrEmpty(retypepass))
            {
                ViewBag.LoiNhap = "Mật khẩu không được để trống!";
            }

            else if (EncryptedData.Encode(oldpassword) != kh.MatKhau)
            {
                ViewData["Loi3"] = "Mật khẩu cũ không đúng!";
            }
            else if (retypepass != newpassword)
            {
                ViewData["Loi2"] = "Mật khẩu nhập lại không khớp!";
            }
            else if (EncryptedData.Encode(newpassword) == kh.MatKhau)
            {
                ViewData["Loi4"] = "Mật khẩu mới không được trùng với mật khẩu cũ!";
            }
            else
            {
                kh.MatKhau = EncryptedData.Encode(newpassword);
                data.SubmitChanges();
                return RedirectToAction("Information", "User");
            }
            return this.Information();

        }
        public ActionResult SignOut()
        {
            Session["Taikhoan"] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "PhoneStore");
        }
    }
}

Views/User/ChangePassword.cshtml
@model ToyStore.Models.KhachHang

@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="section">
    <div class="margin-bottom-20">
        <div class="wrap_background_aside margin-bottom-40 page_login">
            <div class="wrap_background_aside margin-bottom-40">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-lg-offset-3 col-md-offset-3">
                        <div class="page-login">
                            <h1 class="title_heads a-center"><span>Đổi Mật Khẩu</span></h1>
                            <h3 class="a-center"><p style="font-size: 14px">Để bảo mật tài khoản, vui lòng không chia sẻ mật khẩu cho người khác</p></h3>
                            <div id="changepassword">
                                @using (Html.BeginForm())
                                {
                                    @Html.ValidationSummary(true)

                                    <div class="form-signup " style="color:red;">
                                        @ViewBag.LoiTK
                                        @ViewBag.LoiEmail
                                    </div>
                                    <div class="form-signup clearfix">
                                        <div class="row">
                                            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                                                <fieldset class="form-group">
                                                    <label> Nhập Mật Khẩu Cũ<span class="required">*</span></label>
                                                    <input type="password" name="oldpassword" class="form-control form-control-lg" placeholder="Mật khẩu cũ" required="" />
                                                    @ViewData["Loi3"]
                                                </fieldset>
                                            </div>
                                            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                                                <fieldset class="form-group">
                                                    <label>Nhập Mật Khẩu Mới <span class="required">*</span></label>
                                                    <input type="password" name="newpassword" class="form-control form-control-lg" placeholder="Mật khẩu mới" required="" />
                                                    @ViewData["Loi4"]
                                                </fieldset>
                                            </div>
                                            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                                                <fieldset class="form-group">
                                                    <label>Xác Nhận Mật Khẩu Mới <span class="required">*</span></label>
                                                    <input type="password" name="retypepass" class="form-control form-control-lg" placeholder="Xác nhận mật khẩu mới" required="" />
                                                    @ViewData["Loi2"]
                                                </fieldset>
                                            </div>
                                        </div>

                                        <div class="section margin-top-10">
                                            <button type="submit" value="Đăng ký" class="btn btn-primary btn_50">Đổi Mât Khẩu</button>
                                            <h4 style="color: red;text-align: center;">@ViewBag.LoiNhap</h4>
                                            <a href='@Url.Action("Information", "User")' style="float:right;">
                                                <span>
                                                    Trở về hồ sơ cá nhân
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/User/Chitietdonhang.cshtml
@model IEnumerable<ToyStore.Models.ChiTietDatHang>

@{
    ViewBag.Title = "Chi tiết đơn đặt hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page shopping-cart-page">
    <div class="page-body">

        <div class="order-summary-content container">


            <div id="shopping-cart-form" style="display: block;">
                <div class="shopping-cart-info" style="width: 100%">
                    <div class="cart-detail">
                        <div class="table-wrapper">
                            <table class="cart">
                                <colgroup>
                                    <col width="1">
                                    <col width="1">
                                    <col>
                                    <col width="1">
                                    <col width="1">
                                    <col width="1">
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th class="sku">
                                            SKU
                                        </th>
                                        <th class="product-picture">
                                            Hình ảnh
                                        </th>
                                        <th class="product">
                                            Tên sản phẩm
                                        </th>
                                        <th class="unit-price">
                                            Giá bán
                                        </th>
                                        <th class="quantity">
                                            Số lượng
                                        </th>
                                        <th class="quantity">
                                            Toàn bộ
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>

                                            <td class="sku">
                                                <label class="td-title">SKU:</label>
                                                <span class="sku-number"></span>
                                            </td>
                                            <td class="product-picture">
                                                <a href="@Url.Action("Details", "ToyStore", new { id = @item.MaSP })"><img alt="@item.SanPham.TenSP" src="~/Assets/Images/sanPham/@item.SanPham.AnhBia" title="Hiển thị chi tiết cho @item.SanPham.TenSP"></a>
                                                <input type="hidden" class="product-id" value="@item.MaSP">
                                            </td>
                                            <td class="product">
                                                <a href="@Url.Action("Details", "ToyStore", new { id = @item.MaSP })" class="product-name">@item.SanPham.TenSP</a>
                                                <div class="attributes">
                                                    Màu sắc: Đen
                                                </div>
                                            </td>
                                            <td class="unit-price">
                                                <label class="td-title">Giá bán:</label>
                                                <span class="product-unit-price">@String.Format("{0:0,0}", item.DonGia)₫</span>
                                            </td>
                                            <td class="quantity">
                                                <div class="cart-quantity-input-container">
                                                    <input type="text" maxlength="3" readonly min="0" class="qty-input" name="txtSoluong" size="4" value="@item.SoLuong">
                                                </div>
                                            </td>
                                            <td class="quantity">
                                                <label class="td-title">Toàn bộ:</label>
                                                <span class="product-subtotal">@String.Format("{0:0,0}", item.DonGia * item.SoLuong)₫</span>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section id="body" style="margin-bottom: 50px; margin-top: 30px">
    <div class="container">
        <a href="@Url.Action("DonDatHang", "User")">
            <button type="submit" class="btn btn-info center-block" style="width: 100px">Về đơn hàng</button>
        </a>
    </div>
</section>

Views/User/DangKy.cshtml
@{
    ViewBag.Title = "Đăng Ký";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        background: #fff;
    }
</style>

<div class="page registration-page">
    <div class="page-body">
        <div class="customer-blocks">
            <div class="new-wrapper register-block">
                <div class="topic-block">
                    <div class="topic-block-body">
                        <p><img src="~/Assets/Images/shop/register_background.png" alt="" width="793" height="467"></p>
                    </div>
                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <div class="fieldset">
                    <div class="page-title">
                        <h1>Đăng ký</h1>
                    </div>
                    <div class="form-fields">
                        <div class="inputs first_name">
                            <label for="FirstName">Tên đăng nhập:</label>
                            @Html.TextBox("TenDN", null, new { placeholder = "Tên đăng nhập", @class = "form-control form-control-lg" })
                            @ViewData["Loi1"]
                        </div>
                        <div class="inputs">
                            <label for="Username">Họ, Tên:</label>
                            @Html.TextBox("HotenKH", null, new { placeholder = "Họ tên", @class = "form-control form-control-lg" })
                            @ViewData["Loi2"]
                        </div>
                        <div class="inputs">
                            <label for="Email">E-mail:</label>
                            @Html.TextBox("Email", null, new { placeholder = "Email", @class = "form-control form-control-lg" })
                            @ViewData["Loi6"]
                        </div>
                        <div class="inputs">
                            <label for="Phone">Điện thoại:</label>
                            @Html.TextBox("SDT", null, new { placeholder = "Số điện thoai", @class = "form-control form-control-lg" })
                            @ViewData["Loi4"]
                        </div>
                        <div class="inputs">
                            <label for="Phone">Địa chỉ:</label>
                            @Html.TextBox("DiaChi", null, new { placeholder = "Địa chỉ", @class = "form-control form-control-lg" })
                            @ViewData["Loi5"]
                        </div>
                    </div>
                </div>
                <div class="fieldset">
                    <div class="form-fields">
                        <div class="inputs">
                            <label for="Password">Mật khẩu:</label>
                            <input type="password" name="MatKhau" class="form-control form-control-lg" placeholder="Mật khẩu" required="" />
                            @ViewData["Loi7"]
                        </div>
                        <label class="luu_y"> Lưu ý: Mật khẩu phải có tối thiểu 8 ký tự bao gồm chữ, số và các ký tự đặc biệt </label>
                        <div class="inputs">
                            <label for="ConfirmPassword">Xác nhận mật khẩu:</label>
                            <input type="password" name="MatKhauNhapLai" class="form-control form-control-lg" placeholder="Nhập lại mật khẩu" required="" />
                            @ViewData["Loi8"]
                            @ViewData["Loi9"]
                        </div>
                    </div>
                </div>
                <div class="buttons">
                    <button type="submit" name="register-button" id="register-button" class="button-1 register-next-step-button">Đăng ký</button>
                </div>
                <div class="buttons-forgot">
                    <label> Bạn đã có tài khoản? </label>
                    <a href="@Url.Action("DangNhap", "User")" class="link_access">đăng nhập ngay</a>
                </div>
            }
        </div>
    </div>
</div>

Views/User/DonDatHang.cshtml
@model IEnumerable<ToyStore.Models.DonDatHang>

@{
    ViewBag.Title = "Đơn đặt hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="cart_items">
    <div class="container">
        <div class="table-responsive cart_info">
            <table class="table table-condensed text-center" style="margin-bottom: 0px;">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Mã đơn hàng</td>
                        <td class="description">Ngày đặt hàng</td>
                        <td class="quantity">Ngày hẹn giao</td>
                        <td class="price">Số điện thoại</td>
                        <td class="total">Địa chỉ</td>
                        <td class="product-details">Tổng tiền</td>
                        <td class="cart">Thanh toán</td>
                        <td class="cart">Tình trạng</td>
                        <td class="cart"></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td class="cart_product">
                            @item.SoDH
                        </td>
                        <td class="cart_description">
                            @String.Format("{0:dd/MM/yyyy}", item.NgayDH)

                        </td>
                        <td class="cart_quantity">
                            @String.Format("{0:dd/MM/yyyy}", item.NgayGiao)
                        </td>
                        <td class="cart_price">
                            @item.SDT
                        </td>
                        <td class="cart_total">
                            @item.Diachi
                        </td>
                        <td>
                            @String.Format("{0:0,0}", item.TongTien)
                        </td>
                        @if (item.DaThanhToan == false)
                        {
                            <td>Chưa thanh toán</td>
                        }
                        else
                        {
                            <td>Đã thanh toán</td>
                        }
                        @if (item.TinhTrangGiaoHang == false)
                        {
                            <td>Đang vận chuyển</td>
                        }
                        else
                        {
                            <td>Đã giao hàng</td>
                        }
                        <td>
                            @Html.ActionLink("Chi Tiết", "Chitietdonhang", new { id = item.SoDH })
                        </td>
                    </tr>

                    }
                </tbody>
                <tfoot>
                    <tr class="cart_menu">
                        
                    </tr>                    
                </tfoot>
            </table>
        </div>
    </div>
</section> <!--/#cart_items-->
<section id="body" style="margin-bottom: 50px ">
    <div class="container">
        <a href="@Url.Action("Index", "ToyStore")">
            <button type="submit" class="btn btn-info center-block" style="width: 100px">Về trang chủ</button>
        </a>
    </div>
</section>